export const HANDLE_TEXT_INPUT_CHANGE = "HANDLE_TEXT_INPUT_CHANGE";
export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO_COMPLETION = "TOGGLE_TODO_COMPLETION";
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
export const CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS";
