export const ERROR_STATE = "ERROR_STATE";

export const FETCH_TODOS_START = "FETCH_TODOS_START";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";

export const HANDLE_TEXT_INPUT_CHANGE = "HANDLE_TEXT_INPUT_CHANGE";
export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO_COMPLETION = "TOGGLE_TODO_COMPLETION";
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
export const CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS";
